spring.application.name=meu-dog

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/database?currentSchema=meu-dog}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:Admin@123}
spring.datasource.hikari.schema=meu-dog

spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.properties.hibernate.default_schema=meu-dog
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=false
